// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrT0mIq5U4BdPGT6E7Pdq02M4JzmyG3qU',
    appId: '1:207746746055:web:4b5d99f4cfac90d57120e2',
    messagingSenderId: '207746746055',
    projectId: 'bahar-firebase-case-1',
    authDomain: 'bahar-firebase-case-1.firebaseapp.com',
    storageBucket: 'bahar-firebase-case-1.appspot.com',
    measurementId: 'G-C5LSR80F6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiuO3Btn_jW0YVh_DD4SOON131DH6GW7I',
    appId: '1:207746746055:android:978df97f124dbe0a7120e2',
    messagingSenderId: '207746746055',
    projectId: 'bahar-firebase-case-1',
    storageBucket: 'bahar-firebase-case-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVJalUzzHfN_0w58lsIxIsM0SdIKCsjN4',
    appId: '1:207746746055:ios:908f638057d4727c7120e2',
    messagingSenderId: '207746746055',
    projectId: 'bahar-firebase-case-1',
    storageBucket: 'bahar-firebase-case-1.appspot.com',
    iosBundleId: 'com.example.baharFirebaseCase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVJalUzzHfN_0w58lsIxIsM0SdIKCsjN4',
    appId: '1:207746746055:ios:a2b11e93bf15f8627120e2',
    messagingSenderId: '207746746055',
    projectId: 'bahar-firebase-case-1',
    storageBucket: 'bahar-firebase-case-1.appspot.com',
    iosBundleId: 'com.example.baharFirebaseCase.RunnerTests',
  );
}
